run-name: Building PHP Docker images

on:
  schedule:
    - cron: 0 3 * * *
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    env:
      ghcr-image: ghcr.io/${{ github.repository_owner }}/php
      image-tag: ${{ matrix.php }}-${{ matrix.bundle }}-alpine

    strategy:
      fail-fast: true
      matrix:
        php: ["7.4", "8.0", "8.1"]
        bundle: ["cli", "fpm"]

    name: PHP ${{ matrix.php }}-${{ matrix.bundle }}
    runs-on: macos-12
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.ghcr-image }}
          tags: |
            type=sha,prefix=${{ env.image-tag }}-,format=short
            type=raw,value=${{ env.image-tag }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./php
          build-args: |
            BASE_TAG=${{ env.image-tag }}
          file: ./php/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.ghcr-image }}:${{ env.ghcr-image }}
          cache-to: type=inline
